version: '3'

services:
 lab:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: "5000"
   ports:
     - "5000:8080"
 db:
   image: postgres:15.4-alpine3.18
   restart: always
   environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: backend-lab3
      POSTGRES_PASSWORD: postgres
   ports:
     - '5432:5432'